<a href="https://colab.research.google.com/github/SarthakData2026/AI_IN_DATA_SCIENCE/blob/main/Module3/CH3_3_plotly.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
import numpy as np

In [ ]:
#import data set
df=px.data.gapminder()

In [ ]:
df

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,Africa,1987,62.351,9216418,706.157306,ZWE,716
1700,Zimbabwe,Africa,1992,60.377,10704340,693.420786,ZWE,716
1701,Zimbabwe,Africa,1997,46.809,11404948,792.449960,ZWE,716
1702,Zimbabwe,Africa,2002,39.989,11926563,672.038623,ZWE,716
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [ ]:
df.shape

(1704, 8)

In [ ]:
canada_df=px.data.gapminder().query("country=='Canada'")

In [ ]:
canada_df

    country continent  year  lifeExp       pop    gdpPercap iso_alpha  iso_num
240  Canada  Americas  1952   68.750  14785584  11367.16112       CAN      124
241  Canada  Americas  1957   69.960  17010154  12489.95006       CAN      124
242  Canada  Americas  1962   71.300  18985849  13462.48555       CAN      124
243  Canada  Americas  1967   72.130  20819767  16076.58803       CAN      124
244  Canada  Americas  1972   72.880  22284500  18970.57086       CAN      124
245  Canada  Americas  1977   74.210  23796400  22090.88306       CAN      124
246  Canada  Americas  1982   75.760  25201900  22898.79214       CAN      124
247  Canada  Americas  1987   76.860  26549700  26626.51503       CAN      124
248  Canada  Americas  1992   77.950  28523502  26342.88426       CAN      124
249  Canada  Americas  1997   78.610  30305843  28954.92589       CAN      124
250  Canada  Americas  2002   79.770  31902268  33328.96507       CAN      124
251  Canada  Americas  2007   80.653  33390141  36319.23501       CAN      124

#bar chart

In [ ]:
fig=px.bar( canada_df,x='year',y='pop' ,title="canada population status")

In [ ]:
fig=px.bar( canada_df,x='year',y='pop' ,title="canada population status",labels={'pop':'population'})

In [ ]:
fig=px.bar( canada_df,x='year',y='pop' ,title="canada population status",labels={'pop':'population'},color='pop')

In [ ]:
fig.show()

In [ ]:
fig=px.bar( canada_df,x='year',y='pop' ,title="canada population status",labels={'pop':'population'},color='pop',hover_data=['lifeExp'],text='pop')

In [ ]:
fig.show()

In [ ]:
#customize text show in bar
fig.update_traces(texttemplate='%{text:.2s}',textposition='outside')
fig.show()

In [ ]:
#update layout
fig.update_layout(xaxis_tickangle=-45)
fig.show()

In [ ]:
#update layout
fig.update_layout(xaxis_tickangle=-45,yaxis_title='population of canada')
fig.show()

In [ ]:
from tempfile import template
#update layout
fig.update_layout(xaxis_tickangle=-45,yaxis_title='population of canada',template='plotly_dark')
fig.show()

In [ ]:
from tempfile import template
#update layout
fig.update_layout(xaxis_tickangle=-45,yaxis_title='population of canada',template='plotly_dark',uniformtext_minsize=10)
fig.show()

In [ ]:
#update layout
fig.update_layout(xaxis_tickangle=-45,yaxis_title='population of canada',template='plotly_dark',uniformtext_minsize=10,uniformtext_mode='hide')
fig.show()

In [ ]:
#update layout
fig=px.line( canada_df,x='year',y='pop' ,title="canada population status",labels={'pop':'population'},color='pop',hover_data=['lifeExp'],text='pop')
fig.update_layout(xaxis_tickangle=-45,yaxis_title='population of canada',template='plotly_dark',uniformtext_minsize=10,uniformtext_mode='hide')
fig.show()

In [ ]:
#3D scatter plot
df_iris=px.data.iris()

In [ ]:
df_iris

,sepal_length,sepal_width,petal_length,petal_width,species,species_id
0,5.1,3.5,1.4,0.2,setosa,1
1,4.9,3.0,1.4,0.2,setosa,1
2,4.7,3.2,1.3,0.2,setosa,1
3,4.6,3.1,1.5,0.2,setosa,1
4,5.0,3.6,1.4,0.2,setosa,1
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,3
146,6.3,2.5,5.0,1.9,virginica,3
147,6.5,3.0,5.2,2.0,virginica,3
148,6.2,3.4,5.4,2.3,virginica,3
149,5.9,3.0,5.1,1.8,virginica,3

In [ ]:
fig_iris=px.scatter_3d(df_iris,x='sepal_length',y='sepal_width',z='petal_length')
fig_iris.show()

In [ ]:
fig_iris=px.scatter_3d(df_iris,x='sepal_length',y='sepal_width',z='petal_length',color='species')
fig_iris.show()

In [ ]:
canada_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 240 to 251
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    12 non-null     object
 1   continent  12 non-null     object
 2   year       12 non-null     int64
 3   lifeExp    12 non-null     float64
 4   pop        12 non-null     int64
 5   gdpPercap  12 non-null     float64
 6   iso_alpha  12 non-null     object
 7   iso_num    12 non-null     int64
dtypes: float64(2), int64(3), object(3)
memory usage: 864.0+ bytes

In [ ]:
canada_df=px.data.gapminder().query("year==2007")
top_10=canada_df.sort_values('pop',ascending=True).head(10)
df2=px.bar(top_10,x='country',y='pop',color='country')
df2.show()